Node/src/main/java/de/iai/ilcd/model/security/User.java
package de.iai.ilcd.model.security;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap; 
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.PostLoad;
import javax.persistence.PostUpdate;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.ObjectUtils;

import de.iai.ilcd.util.SodaUtil;

/**
 * 
 * @author clemens.duepmeier
 */
@Entity
@Table( name = "user" )
public class User implements ISecurityEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue( strategy = GenerationType.IDENTITY )
	private Long id;

	@Column( unique = true )
	private String userName;

	@Column( name = "PASSWORD_HASH" )
	private String passwordHash;

	@Column( name = "PASSWORD_HASH_SALT" )
	private String passwordHashSalt;

	private String firstName;

	private String lastName;

	private String title;

	@Enumerated( EnumType.STRING )
	private Gender gender = null;

	private String institution;
	
	private String phone;
	
	private String email;

	private String registrationKey;

	private String dsPurpose;

	private String jobPosition;
	
	@Column( unique = true)
	private String apiKey;
	
	@Column( name = "apikeyexpiry")
	private Date apiKeyExpiry;
	
	@Column( name = "apikeyallowed")
	private Boolean apiKeyAllowed = true;

	@Transient
	private Boolean licenseConditions = false;

	@Column( name = "acceptedAddTerms")
	private Boolean acceptedAdditionalTerms = false;

	@Embedded
	private Address address = new Address();

	@ManyToMany( mappedBy = "users", fetch = FetchType.EAGER, cascade = { CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.DETACH } )
	// Does not contain CascadeType.REMOVE
	private List<UserGroup> groups = new ArrayList<UserGroup>();

	@Basic
	@Column( name = "super_admin_permission" )
	private boolean superAdminPermission;

	/**
	 * The organization of the user
	 */
	@ManyToOne( optional = true )
	@JoinColumn( name = "organization", nullable = true )
	private Organization organization;
	
	@Basic
	@Column( name = "privacy_policy_accepted" )
	private Boolean privacyPolicyAccepted;
	
	@Basic
	@Column( name = "password_expired")
	private Boolean passwordExpired;
	

	@ElementCollection( targetClass = String.class )
	@CollectionTable( name = "user_sector", joinColumns = @JoinColumn( name = "User_ID" ))
	private List<String> sector = new ArrayList<String>();
	
	@ElementCollection
	@CollectionTable( name = "user_acceptedaddterms", joinColumns = @JoinColumn( name = "User_ID" ))
	@MapKeyColumn(name="additionalterm")
	@Column(name="accepted")
	private Map<String, Boolean> acceptedAdditionalTermsMap = new HashMap<String, Boolean>();

	@Basic
	@Column( name = "sector_other" )
	private String sectorOther;

	@Column( name = "resetkey" )
	private String resetKey;
	
	@Column( name = "resettimestamp" )
	private Date resetTimestamp;
	
	
	@Override
	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress( Address address ) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail( String email ) {
		this.email = email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName( String firstName ) {
		this.firstName = firstName;
	}
	
	public String getInstitution() {
		return institution;
	}
	
	public void setInstitution(String institution) {
		this.institution = institution;
	}
	
	public String getPhone() {
		return phone;
	}
	
	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Gender getGender() {
		return this.gender;
	}

	public void setGender( Gender gender ) {
		this.gender = gender;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName( String lastName ) {
		this.lastName = lastName;
	}

	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash( String passwordHash ) {
		this.passwordHash = passwordHash;
	}

	public String getPasswordHashSalt() {
		return this.passwordHashSalt;
	}

	public void setPasswordHashSalt( String passwordHashSalt ) {
		this.passwordHashSalt = passwordHashSalt;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle( String title ) {
		this.title = title;
	}

	public String getUserName() {
		return this.userName;
	}
	
	public String getResetKey() {
		return resetKey;
	}
	
	public void setResetKey(String resetKey) {
		this.resetKey = resetKey;
	}
	
	public Date getResetTimestamp() {
		return resetTimestamp;
	}
	
	public void setResetTimestamp(Date resetTimestamp) {
		this.resetTimestamp = resetTimestamp;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getDisplayName() {
		return this.userName;
	}

	public void setUserName( String userName ) {
		this.userName = userName;
	}

	public String getRegistrationKey() {
		return this.registrationKey;
	}

	public void setRegistrationKey( String registrationKey ) {
		this.registrationKey = registrationKey;
	}

	public boolean isActivated() {
		return registrationKey == null;
	}

	public List<UserGroup> getGroups() {
		return this.groups;
	}

	protected void setGroups( List<UserGroup> groups ) {
		this.groups = groups;
	}

	public String getDsPurpose() {
		return this.dsPurpose;
	}

	public void setDsPurpose(String dspurpose) {
		this.dsPurpose = dspurpose;
	}

	public String getJobPosition() {
		return this.jobPosition;
	}

	public void setJobPosition( String jobPosition ) {
		this.jobPosition = jobPosition;
	}

	public Boolean getAcceptedAdditionalTerms() {
		return acceptedAdditionalTerms;
	}

	public void setAcceptedAdditionalTerms(Boolean acceptedAdditionalTerms) {
		this.acceptedAdditionalTerms = acceptedAdditionalTerms;
	}
	
	public void setAcceptedAdditionalTermsMap(Map<String, Boolean> acceptedAdditionalTermsMap) {
		this.acceptedAdditionalTermsMap= acceptedAdditionalTermsMap;
	}
	
	public Map<String, Boolean> getAcceptedAdditionalTermsMap() {
		return this.acceptedAdditionalTermsMap;
	}

	
	public String getApiKey() {
		return apiKey;
	}
	
	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	} 
	
	public Date getApiKeyExpiry() {
		return apiKeyExpiry;
	}
	
	public String getApiKeyExpiryString() {
		if (apiKeyExpiry != null) {
			return apiKeyExpiry.toString();
		}
		return "---";
	}
	
	public void setApiKeyExpiry(Date apiKeyExpiry) {
		this.apiKeyExpiry = apiKeyExpiry;
	}
	
	public Boolean isApiKeyAllowed() {
			return apiKeyAllowed;

	}

	public void setApiKeyAllowed(boolean apiKeyAllowed) {
		this.apiKeyAllowed = apiKeyAllowed;
	}
	
	/**
	 * 
	 * @param group
	 */
	public void addToGroup( UserGroup group ) {
		if ( !this.groups.contains( group ) ) {
			this.groups.add( group );
			group.addUser( this );
		}
	}

	public void removeFromGroup( UserGroup group ) {
		if ( this.groups.contains( group ) ) {
			this.groups.remove( group );
		}
	}

	public void removeFromAllGroups() {
		List<UserGroup> allGroups = new ArrayList<UserGroup>();
		allGroups.addAll( this.groups );
		for ( UserGroup group : allGroups ) {
			group.removeUser( this ); // this removes the group also locally
		}
	}

	/**
	 * Get the organization of this user
	 * 
	 * @return organization of this user
	 */
	public Organization getOrganization() {
		return this.organization;
	}

	/**
	 * Set the organization of this user
	 * 
	 * @param organization
	 *            organization of this user to set
	 */
	public void setOrganization( Organization organization ) {
		if ( ObjectUtils.equals( this.organization, organization ) ) {
			return;
		}
		Organization oldOrg = this.organization;
		this.organization = organization;

		if ( oldOrg != null ) {
			oldOrg.removeUser( this );
		}

		if ( this.organization != null ) {
			this.organization.addUser( this );
		}
	}
	
	public boolean isPrivacyPolicyAccepted() {
		return this.privacyPolicyAccepted != null ? this.privacyPolicyAccepted : false;
	}
	
	public void setPrivacyPolicyAccepted(boolean privacyPolicyAccepted) {
		this.privacyPolicyAccepted = privacyPolicyAccepted;
	}
	
	public Boolean isPasswordExpired() {
		return passwordExpired;
	}

	public void setPasswordExpired(Boolean passwordExpired) {
		this.passwordExpired = passwordExpired;
	}

	public Boolean getLicenseConditions() {
		return licenseConditions;
	}

	public void setLicenseConditions(Boolean licenseConditions) {
		this.licenseConditions = licenseConditions;
	}
	
	public List<String> getSector() {
		return sector;
	}

	public void setSector(List<String> sector) {
		this.sector = new ArrayList<String>(sector);
	}
	
	public String getSectorAsString() {
		StringBuffer buf = new StringBuffer();
		for (String s : this.sector) {
			if (buf.length() != 0) {
				buf.append(";");
			}
			buf.append(s);
		}
		return buf.toString();
	}

	public String getSectorOther() {
		return sectorOther;
	}

	public void setSectorOther(String sectorOther) {
		this.sectorOther = sectorOther;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
		result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
		return result;
	}

	@Override

Node/src/main/java/de/iai/ilcd/jmx/ApplicationInfoMBean.java
package de.iai.ilcd.jmx;

public interface ApplicationInfoMBean {
	public String getVersion();

	public String getSchemaVersion();

	public String getNodeId();
}

Node/src/main/java/de/iai/ilcd/webgui/controller/admin/CustomReportsBean.java
package de.iai.ilcd.webgui.controller.admin;

import java.io.IOException;
import java.util.List;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.jsf.FacesContextUtils;

import de.iai.ilcd.model.common.ReportConfig;
import de.iai.ilcd.service.CustomReportService;

/**
 * The managed bean for retrieving customized reports.
 * 
 * @author sarai
 *
 */
@ManagedBean(name = "customReportsBean")
@ApplicationScoped
public class CustomReportsBean {

	private Logger log = LoggerFactory.getLogger(this.getClass());
	
	private CustomReportService customReportService;

	public CustomReportsBean() {
		WebApplicationContext ctx = FacesContextUtils.getWebApplicationContext(FacesContext.getCurrentInstance());
		this.customReportService = ctx.getBean(CustomReportService.class);
	}

	public List<ReportConfig> getReportConfigs() {
		return customReportService.getReportConfigs();
	}

	/**
	 * Checks whether custom reports are enabled.
	 * 
	 * @return true if at least one custom report is set.
	 */
	public boolean isCustomReportsEnabled() {
		return (customReportService.getReportConfigs() != null)
				&& !customReportService.getReportConfigs().isEmpty();
	}

	/**
	 * Executes an SQL query for a report and write result directly to the response
	 * 
	 * @param request
	 *            The request to execute
	 * @param fileName
	 *            he desired file name of csv result
	 * 
	 */
	public void executeSQL(final ReportConfig report) {
		try {			
			String fileName = new String(report.getFileName()).replace(" ", "_");
			if (report.isTimeStampSuffix()) {
				DateTimeFormatter dtf = DateTimeFormat.forPattern("yyyy-MM-dd_HH-mm");
				fileName +=  "_" + dtf.print(new DateTime());
			}
			fileName += ".csv";
			if (log.isDebugEnabled())
				log.debug("filename is " + fileName);

			FacesContext facesContext = FacesContext.getCurrentInstance();
			ExternalContext externalContext = facesContext.getExternalContext();
			externalContext.setResponseContentType("text/csv");
			externalContext.setResponseHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\"");

			customReportService.executeSQLQuery(report, externalContext.getResponseOutputStream());
			
			facesContext.responseComplete();
		} catch (IOException e) {
			log.error("Error writing response", e);
			if (log.isDebugEnabled()) 
				e.printStackTrace();
		}
	}
	
	public CustomReportService getReportService() {
		return this.customReportService;
	}

}

Node/src/main/webapp/admin/addressInfoPanel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:ui="http://java.sun.com/jsf/facelets">
<!-- 
ui:params:
	- countries: country list
	- chosenCountry: chosen country
	- address: address instance
 -->
<ui:param name="backingBean" value="#{contactListHandler}" />
    <p:panel header="#{i18n['admin.user.addrInfo']}">
        <h:panelGrid columns="2">
            <p:outputLabel value="#{i18n['admin.user.country']}:" for="country" />
            <!-- Fix with 150px due to problems with tabs: (usage with orgEntry)
                 dynamic=true for tabs ==> null value set for selectOneMenu
                 dynamic=false ==> selectOneMenu styling bug, set manually -->
            <p:selectOneMenu style="width:150px" id="country" value="#{chosenCountry}" converter="geoAreaConverter">
                <f:selectItem itemLabel="#{i18n['common.select.hint']}" itemValue="0" />
                <f:selectItems value="#{countries}" var="country" itemLabel="#{country.name}" itemValue="#{country}" />
            </p:selectOneMenu>
        </h:panelGrid>
        <h:panelGrid columns="4">
            <p:outputLabel value="#{i18n['admin.user.zipCode']}:" for="zipCode" />
            <p:inputText id="zipCode" value="#{address.zipCode}" maxlength="50" size="10" />
            <p:outputLabel value="#{i18n['admin.user.city']}:" for="city" />
            <p:inputText id="city" value="#{address.city}" maxlength="50" size="30" />
        </h:panelGrid>
        <h:panelGrid>
            <p:outputLabel value="#{i18n['admin.user.streetAddr']}:" for="streetAddr" />
            <p:inputTextarea id="streetAddr" value="#{address.streetAddress}" cols="72" rows="10" />
        </h:panelGrid>
    </p:panel>
</ui:composition>

Node/src/main/webapp/admin/manageNodeList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:body>
        <ui:composition template="/admin/layout/adminDesign.xhtml">
            <ui:param name="pageTitle" value="#{i18n['admin.node.manageList']}" />
            <ui:define name="content">
                <h:form id="tableForm" prependId="false">
               	
                    <p:commandButton id="deleteBtn"
                                     value="#{i18n['admin.deleteSelected']}"
                                     onclick="PF('confirmDelete').show()"
                                     type="button"
                                     disabled="#{nodeListHandler.nothingSelected}" />
                    <p:confirmDialog message="#{i18n['admin.confirmMsg.deleteSelected']}?"
                                     header="#{i18n['admin.confirmDlg.delete']}"
                                     severity="alert"
                                     widgetVar="confirmDelete">
                        <div class="confirmDlgButtons">
                            <p:commandButton value="#{i18n['admin.cancel']}"
                                             type="button"
                                             onclick="PF('confirmDelete').hide()" />
                            <p:commandButton value="#{i18n['admin.ok']}"
                                             action="#{nodeListHandler.deleteSelected}"
                                             oncomplete="PF('confirmDelete').hide()"
                                             ajax="false"
                                             update="messages nodeTable" />
                        </div>
                    </p:confirmDialog>

                    <ui:include src="/messages.xhtml" />

                    <p:dataTable id="nodeTable"
                                 var="node" 
                                 value="#{nodeListHandler.lazyModel}"
                                 lazy="true"
                                 paginator="true"
                                 rows="15" rowsPerPageTemplate="5,10,15,50"
                                 selection="#{nodeListHandler.selectedNodes}"
                                 paginatorTemplate="{CurrentPageReport} {FirstPageLink}
                                 {PreviousPageLink} {PageLinks} {NextPageLink}
                                 {LastPageLink} {RowsPerPageDropdown} #{i18n['common.list.entriesPerPage']}
                                 (#{nodeListHandler.lazyModel.rowCount} #{i18n['common.list.total']})"
                                 emptyMessage="#{i18n['common.list.noneFound']}">
                        
                        <p:ajax event="rowSelectCheckbox" process="@this" update="@(#deleteBtn)" />
                        <p:ajax event="rowUnselectCheckbox" process="@this" update="@(#deleteBtn)" />
                        <p:ajax event="toggleSelect" process="@this" update="@(#deleteBtn)" />
                                 
                        <p:column style="text-align: center;" selectionMode="multiple" />

                        <p:column headerText="#{i18n['common.node.id']}">
                            <h:link outcome="#{url.node.edit}" value="#{node.nodeId}">
                                <f:param name="nodeId" value="#{node.id}" />
                            </h:link>
                        </p:column>

                        <p:column headerText="#{i18n['common.name']}">
                            <h:outputText value="#{node.name}" />
                        </p:column>

                        <p:column headerText="#{i18n['admin.node.baseURL']}">
                            <h:outputText value="#{node.baseUrl}" />
                        </p:column>
                    </p:dataTable>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Node/src/main/webapp/admin/quantitativeQualityCheck.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<ui:composition>
	<h:form id="validation" prependId="true">
		<p:accordionPanel id="qqaAcordionPanel"
			activeIndex="#{validationHandler.activeIndex}">
			<p:tab title="#{i18n['admin.qualityChecker.accordion.title']}">
				<p:growl id="growl" showDetail="true" sticky="false" />
				<div>
					<div class="clearLeft">
						<p:dataTable id="sourceStockTable" var="source"
							value="#{automaticQualityCheckHandler.stockListHandler.lazyModel}"
							selection="#{automaticQualityCheckHandler.selectedStocks}"
							emptyMessage="#{i18n['common.list.noneFound']}" lazy="true"
							paginator="true" rows="15" draggableRows="false"
							rowsPerPageTemplate="5,10,15,50"
							paginatorTemplate="{CurrentPageReport} {FirstPageLink}
  		                                 {PreviousPageLink} {PageLinks} {NextPageLink}  
 		                                 {LastPageLink} {RowsPerPageDropdown} #{i18n['common.list.entriesPerPage']} 
 		                                 (#{automaticQualityCheckHandler.stockListHandler.lazyModel.rowCount} #{i18n['common.list.total']})"
							rowStyleClass="#{Constants.DEFAULT_ROOTSTOCK_ID == source.id ? 'unselectable':''}"
							widgetVar="sourceTable" style="width:50%;" sortBy="#{source.id}">

							<p:ajax event="rowSelectCheckbox" process="@this"
								update="@(.categorieswidth)" />
							<p:ajax event="rowUnselectCheckbox" process="@this"
								update="@(.categorieswidth)" />
							<p:ajax event="toggleSelect" process="@this"
								update="@(.categorieswidth)" />

							<p:column style="text-align: center;" selectionMode="multiple"
								width="20px;" />

							<p:column headerText="#{i18n['admin.stock.id']}">
								<h:outputText id="sourceID" value="#{source.name}" />
								<p:tooltip id="tooltipSourceUuid" for="sourceID"
									value="UUID: #{source.uuid.uuid}" />
							</p:column>

							<p:column headerText="#{i18n['admin.stock.name']}">
								<h:outputText value="#{source.description.value}" />
							</p:column>
						</p:dataTable>


						<p:panelGrid columns="3" layout="grid" styleClass="ui-noborder"
							style="width: 50%;">
							<p:panel>
								<p:outputLabel for="thresholdId"
									value="#{i18n['admin.qualityChecker.accordion.threshold']}" />
								<p:spacer width="10" />
								<p:spinner id="thresholdId"
									value="#{automaticQualityCheckHandler.threshold}" min="0"
									size="10" />
								<p:spacer width="5" />
								<h:outputText value="%" />
							</p:panel>
							<p:panel styleClass="warnThreshold">
								<p:outputLabel for="thresholdWarnId"
									value="#{i18n['admin.qualityChecker.accordion.warnThreshold']}"
									styleClass="warnThreshold" />
								<p:spacer width="10" />
								<p:spinner id="thresholdWarnId"
									value="#{automaticQualityCheckHandler.warnThreshold}" min="0"
									size="10" />
								<p:spacer width="5" />
								<h:outputText value="%" />
							</p:panel>
							<p:panel>
								<p:outputLabel value="#{i18n['admin.qualityCheck.showAll']}"
									for="showAllId" />
								<p:selectBooleanCheckbox id="showAllId"
									value="#{automaticQualityCheckHandler.showAll}" />
							</p:panel>
						</p:panelGrid>
					</div>
				</div>
				<div class="categorieswidth">
					<p:commandButton styleClass="categorieswidth" id="qualityCheckBtn"
						widgetVar="qualityCheckBtn"
						action="#{automaticQualityCheckHandler.check}"
						value="#{i18n['admin.qualityCheck.doQualityCheck']}" ajax="true"
						disabled="#{automaticQualityCheckHandler.noStockSelected}"
						onclick="PF('eventTable').clearFilters()"
						actionListener="#{automaticQualityCheckHandler.clearAllFilters}"
						update="logTable,resetEvents,growl,exportLogs,sourceStockTable" />
				</div>
				<div>
					<ui:include src="qualityCheckResults.xhtml" />
				</div>
			</p:tab>
		</p:accordionPanel>
	</h:form>

</ui:composition>
</html>

Node/src/main/webapp/admin/validationResults.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<ui:composition>

	<div>
	    <p:outputLabel value="#{i18n['admin.validation.section.results']}" styleClass="margine checkboxalign" />
		<p:commandButton id="exportLogs" value="#{i18n['admin.validation.log.export']}" disabled="#{empty validationHandler.events}" update="logTable,resetEvents" ajax="false">
			<p:dataExporter type="xls" target="logTable" postProcessor="#{validationResultDocumentView.postProcessXLS}" fileName="#{validationHandler.stockName}_log" />
		</p:commandButton>
	    <p:commandButton styleClass="buttonvalid" id="resetEvents" value="#{i18n['admin.validation.log.export.reset']}" actionListener="#{validationHandler.clearEvents}" disabled="#{empty validationHandler.events}" update="logTable,exportLogs,resetEvents,progressBar" >
		</p:commandButton>
	</div>

	<p:importEnum type="de.iai.ilcd.webgui.util.ValidationContext"
		var="ValidationContext" />
	<p:importEnum type="com.okworx.ilcd.validation.common.DatasetType"
		var="ValidationDatasetType" />

	<p:dataTable id="logTable" emptyMessage="" var="event"
		value="#{validationHandler.events}" widgetVar="eventTable"
		tableStyle="width:auto">

		<p:column headerText="#{i18n['admin.validation.log.table.severity']}"
			sortBy="#{event.severity}">
			<h:outputText value="#{event.severity}" />
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.aspect']}"
			sortBy="#{event.aspect}">
			<h:outputText value="#{event.aspect}" />
		</p:column>

		<p:column
			headerText="#{i18n['admin.validation.log.table.reference.name']}"
			sortBy="#{event.reference.name}">
			<h:outputText value="#{event.reference.name}" />
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.type']}"
			sortBy="#{event.reference.type.value}">
			<h:outputText value="#{event.reference.type.value}" />
		</p:column>

		<p:column headerText="UUID" sortBy="#{event.reference.uuid}" exportable="false">
			<c:choose>
				<c:when
					test="#{validationHandler.validationContext==ValidationContext.DATASETS or validationHandler.validationContext==ValidationContext.STOCK}">
					<h:outputLink
						value="#{request.contextPath}#{validationHandler.goToDataset(event.reference.uuid, event.reference.version, event.reference.type)}"
						target="_blank">
						<h:outputText value="#{event.reference.uuid}" />
					</h:outputLink>
				</c:when>
				<c:otherwise>
					<h:outputText value="#{event.reference.uuid}" />
				</c:otherwise>
			</c:choose>
		</p:column>
		
		<p:column visible="false" headerText="UUID">
			<h:outputText value="#{event.reference.uuid}" />
		</p:column>

		<p:column headerText="#{i18n['admin.proc.version']}">
			<h:outputText value="#{event.reference.version}" />
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.processes']}" exportable="false">
			<ui:fragment rendered="#{event.reference.type eq ValidationDatasetType.FLOW}">
				<ui:repeat var="reference" value="#{validationHandler.getRefsToProcessesForFlow(event.reference.uuid)}">
					<h:outputLink
						value="#{request.contextPath}#{validationHandler.goToDataset(reference.uuid, reference.version, reference.type, true)}"
						target="_blank">
						<h:outputText value="#{reference.name}" />
						<br/> 
					</h:outputLink>
				</ui:repeat>
			</ui:fragment>
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.processes']}" visible="false">
				<h:outputText value="#{validationHandler.getRefsAsString(validationHandler.getRefsToProcessesForFlow(event.reference.uuid))}" /> 
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.message']}"
			sortBy="#{event.message}">
			<h:outputText value="#{event.message}" />
		</p:column>
	</p:dataTable>
</ui:composition>
</html>